---
platform: linux
inputs:
- name: pcf-start-stop
image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse
run:
  path: bash
  args:
  - -c
  - |
    set -e
    export ID=`date +%s`
    export BOSH_CMD="/tmp/${ID}/pcf-start-stop/${TARGET}.sh ${START_STOP}"
    pcf-start-stop/ci/tasks/remote-bosh.sh