---
resources:
- name: pcf-start-stop
  type: git
  source:
    uri: https://github.com/making/pcf-start-stop
    branch: master
- name: every4am
  type: time
  source:
    interval: 24h
    location: Asia/Tokyo
    start: 4:00 AM
    stop: 7:00 AM
jobs:
- name: start-ert
  plan:
  - get: pcf-start-stop
  - task: start-ert
    params: &OPSMGR
      OPSMGR_HOST: {{opsmgr-host}}
      OPSMGR_SSH_USER: {{opsmgr-ssh-user}}
      OPSMGR_SSH_KEY: {{opsmgr-ssh-key}}
      BOSH_DIRECTOR_IP: {{bosh-director-ip}}
      BOSH_USER: {{bosh-user}}
      BOSH_PASSWORD: {{bosh-password}}
      START_STOP: start
      TARGET: pcf-1.10
    file: pcf-start-stop/ci/tasks/pcf-start-stop.yml
- name: stop-ert
  plan:
  - get: every4am
    trigger: true
  - get: pcf-start-stop
  - task: stop-ert
    params:
      <<: *OPSMGR
      START_STOP: stop
      TARGET: pcf-1.10
    file: pcf-start-stop/ci/tasks/pcf-start-stop.yml
- name: smoke-test-ert
  plan:
  - get: pcf-start-stop
  - task: start-ert
    params:
      <<: *OPSMGR
    file: pcf-start-stop/ci/tasks/smoke-test-ert.yml
- name: stop-jmx-bridge
  plan:
  - get: every4am
    passed:
    - stop-ert
    trigger: true
  - get: pcf-start-stop
  - task: stop-jmx-bridge
    params:
      <<: *OPSMGR
      START_STOP: stop
      TARGET: jmx-bridge
    file: pcf-start-stop/ci/tasks/pcf-start-stop.yml
- name: stop-stackdriver-nozzle
  plan:
  - get: every4am
    passed:
    - stop-jmx-bridge
    trigger: true
  - get: pcf-start-stop
  - task: stop-stackdriver-nozzle
    params:
      <<: *OPSMGR
      START_STOP: stop
      TARGET: stackdriver-nozzle
    file: pcf-start-stop/ci/tasks/pcf-start-stop.yml


